#!/bin/bash

if [ $# -lt 2 ]; then
   echo "Error, please pass at least 2 arguments."
   exit 1
fi

if [ ! -f $1 ]; then
   echo "Warning, $1 already exists."
fi

if [ ! -f $2 ]; then
   echo "Error, input file $2 does not exist."
   exit 1
fi

# Duplicates are not removed
grep -Eo "(http|https)://courses.cs.washington.edu/courses/cse[0-9][0-9][0-9]/" $2 > $1

sed 's/\/$/\/21sp\//' -i $1

exit 0